### ISSUE TITLE
Add --version option to mark

### ISSUE THREAD

**Issue by johnblommers** [relston/mark#6]
The command `mark --version`  is not valid.
Consider adding the `--version` commandline option.
Otherwise, one has to

```
pipx upgrade mark
```
This does display the version, but is a tad clumsy.

**Comment by relston** [comment]
I like it!

**Comment by relston** [comment]
Knocked it out. Thanks for the feedback!

**Comment by johnblommers** [comment]
> Knocked it out. Thanks for the feedback!

I just updated `mark` and sure enough `mark --version` works perfectly. A nice touch indeed!
